/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/forms';
import * as import6 from '../../app/app-routing.module';
import * as import7 from '@angular/http';
import * as import8 from 'angular-in-memory-web-api/in-memory-web-api.module';
import * as import9 from '../../app/in-memory-data.service';
import * as import10 from '../../app/hero.service';
import * as import11 from '../../app/hero-search.service';
import * as import12 from './dashboard.component.ngfactory';
import * as import13 from './heroes.component.ngfactory';
import * as import14 from './hero-detail.component.ngfactory';
import * as import15 from './app.component.ngfactory';
import * as import16 from '../../app/dashboard.component';
import * as import17 from '../../app/heroes.component';
import * as import18 from '../../app/hero-detail.component';
import * as import19 from 'angular-in-memory-web-api/in-memory-backend.service';
class AppModuleInjector extends import0.ɵNgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _NgProbeToken_2:any[];
  _ɵg_3:import3.ɵg;
  _APP_INITIALIZER_4:any[];
  _ApplicationInitStatus_5:import0.ApplicationInitStatus;
  _ɵf_6:import0.ɵf;
  _ApplicationRef_7:any;
  _ApplicationModule_8:import0.ApplicationModule;
  _BrowserModule_9:import4.BrowserModule;
  _ɵba_10:import5.ɵba;
  _FormsModule_11:import5.FormsModule;
  _ɵa_12:any;
  _UrlSerializer_13:import3.DefaultUrlSerializer;
  _RouterOutletMap_14:import3.RouterOutletMap;
  _ROUTER_CONFIGURATION_15:any;
  _LocationStrategy_16:any;
  _Location_17:import2.Location;
  _Compiler_18:import0.Compiler;
  _NgModuleFactoryLoader_19:import0.SystemJsNgModuleLoader;
  _ROUTES_20:any[];
  _Router_21:any;
  _RouterModule_22:import3.RouterModule;
  _AppRoutingModule_23:import6.AppRoutingModule;
  _HttpModule_24:import7.HttpModule;
  _InMemoryWebApiModule_25:import8.InMemoryWebApiModule;
  _AppModule_26:import1.AppModule;
  __LOCALE_ID_27:any;
  __NgLocalization_28:import2.NgLocaleLocalization;
  __APP_ID_29:any;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __DomSanitizer_32:import4.ɵe;
  __Sanitizer_33:any;
  __HAMMER_GESTURE_CONFIG_34:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_35:any[];
  __EventManager_36:import4.EventManager;
  __ɵDomSharedStylesHost_37:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_38:import4.ɵDomRendererFactory2;
  __RendererFactory2_39:any;
  __ɵSharedStylesHost_40:any;
  __Testability_41:import0.Testability;
  __Meta_42:import4.Meta;
  __Title_43:import4.Title;
  __ɵi_44:import5.ɵi;
  __ActivatedRoute_45:any;
  __NoPreloading_46:import3.NoPreloading;
  __PreloadingStrategy_47:any;
  __RouterPreloader_48:import3.RouterPreloader;
  __PreloadAllModules_49:import3.PreloadAllModules;
  __ROUTER_INITIALIZER_50:any;
  __APP_BOOTSTRAP_LISTENER_51:any[];
  __InMemoryDbService_52:import9.InMemoryDataService;
  _InMemoryBackendConfig_53:any;
  __XHRBackend_54:any;
  __RequestOptions_55:import7.BaseRequestOptions;
  __Http_56:any;
  __BrowserXhr_57:import7.BrowserXhr;
  __ResponseOptions_58:import7.BaseResponseOptions;
  __XSRFStrategy_59:any;
  __HeroService_60:import10.HeroService;
  __HeroSearchService_61:import11.HeroSearchService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import12.DashboardComponentNgFactory,
      import13.HeroesComponentNgFactory,
      import14.HeroDetailComponentNgFactory,
      import15.AppComponentNgFactory
    ]
    ,[import15.AppComponentNgFactory]);
  }
  get _LOCALE_ID_27():any {
    if ((this.__LOCALE_ID_27 == null)) { (this.__LOCALE_ID_27 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_27;
  }
  get _NgLocalization_28():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_28 == null)) { (this.__NgLocalization_28 = new import2.NgLocaleLocalization(this._LOCALE_ID_27)); }
    return this.__NgLocalization_28;
  }
  get _APP_ID_29():any {
    if ((this.__APP_ID_29 == null)) { (this.__APP_ID_29 = import0.ɵg()); }
    return this.__APP_ID_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == null)) { (this.__IterableDiffers_30 = import0.ɵl()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == null)) { (this.__KeyValueDiffers_31 = import0.ɵm()); }
    return this.__KeyValueDiffers_31;
  }
  get _DomSanitizer_32():import4.ɵe {
    if ((this.__DomSanitizer_32 == null)) { (this.__DomSanitizer_32 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_32;
  }
  get _Sanitizer_33():any {
    if ((this.__Sanitizer_33 == null)) { (this.__Sanitizer_33 = this._DomSanitizer_32); }
    return this.__Sanitizer_33;
  }
  get _HAMMER_GESTURE_CONFIG_34():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_34 == null)) { (this.__HAMMER_GESTURE_CONFIG_34 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_34;
  }
  get _EVENT_MANAGER_PLUGINS_35():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_35 == null)) { (this.__EVENT_MANAGER_PLUGINS_35 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_34)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_35;
  }
  get _EventManager_36():import4.EventManager {
    if ((this.__EventManager_36 == null)) { (this.__EventManager_36 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_35,this.parent.get(import0.NgZone))); }
    return this.__EventManager_36;
  }
  get _ɵDomSharedStylesHost_37():import4.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_37 == null)) { (this.__ɵDomSharedStylesHost_37 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_37;
  }
  get _ɵDomRendererFactory2_38():import4.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_38 == null)) { (this.__ɵDomRendererFactory2_38 = new import4.ɵDomRendererFactory2(this._EventManager_36,this._ɵDomSharedStylesHost_37)); }
    return this.__ɵDomRendererFactory2_38;
  }
  get _RendererFactory2_39():any {
    if ((this.__RendererFactory2_39 == null)) { (this.__RendererFactory2_39 = this._ɵDomRendererFactory2_38); }
    return this.__RendererFactory2_39;
  }
  get _ɵSharedStylesHost_40():any {
    if ((this.__ɵSharedStylesHost_40 == null)) { (this.__ɵSharedStylesHost_40 = this._ɵDomSharedStylesHost_37); }
    return this.__ɵSharedStylesHost_40;
  }
  get _Testability_41():import0.Testability {
    if ((this.__Testability_41 == null)) { (this.__Testability_41 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_41;
  }
  get _Meta_42():import4.Meta {
    if ((this.__Meta_42 == null)) { (this.__Meta_42 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_42;
  }
  get _Title_43():import4.Title {
    if ((this.__Title_43 == null)) { (this.__Title_43 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_43;
  }
  get _ɵi_44():import5.ɵi {
    if ((this.__ɵi_44 == null)) { (this.__ɵi_44 = new import5.ɵi()); }
    return this.__ɵi_44;
  }
  get _ActivatedRoute_45():any {
    if ((this.__ActivatedRoute_45 == null)) { (this.__ActivatedRoute_45 = import3.ɵf(this._Router_21)); }
    return this.__ActivatedRoute_45;
  }
  get _NoPreloading_46():import3.NoPreloading {
    if ((this.__NoPreloading_46 == null)) { (this.__NoPreloading_46 = new import3.NoPreloading()); }
    return this.__NoPreloading_46;
  }
  get _PreloadingStrategy_47():any {
    if ((this.__PreloadingStrategy_47 == null)) { (this.__PreloadingStrategy_47 = this._NoPreloading_46); }
    return this.__PreloadingStrategy_47;
  }
  get _RouterPreloader_48():import3.RouterPreloader {
    if ((this.__RouterPreloader_48 == null)) { (this.__RouterPreloader_48 = new import3.RouterPreloader(this._Router_21,this._NgModuleFactoryLoader_19,this._Compiler_18,this,this._PreloadingStrategy_47)); }
    return this.__RouterPreloader_48;
  }
  get _PreloadAllModules_49():import3.PreloadAllModules {
    if ((this.__PreloadAllModules_49 == null)) { (this.__PreloadAllModules_49 = new import3.PreloadAllModules()); }
    return this.__PreloadAllModules_49;
  }
  get _ROUTER_INITIALIZER_50():any {
    if ((this.__ROUTER_INITIALIZER_50 == null)) { (this.__ROUTER_INITIALIZER_50 = import3.ɵi(this._ɵg_3)); }
    return this.__ROUTER_INITIALIZER_50;
  }
  get _APP_BOOTSTRAP_LISTENER_51():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_51 == null)) { (this.__APP_BOOTSTRAP_LISTENER_51 = [this._ROUTER_INITIALIZER_50]); }
    return this.__APP_BOOTSTRAP_LISTENER_51;
  }
  get _InMemoryDbService_52():import9.InMemoryDataService {
    if ((this.__InMemoryDbService_52 == null)) { (this.__InMemoryDbService_52 = new import9.InMemoryDataService()); }
    return this.__InMemoryDbService_52;
  }
  get _XHRBackend_54():any {
    if ((this.__XHRBackend_54 == null)) { (this.__XHRBackend_54 = import8.inMemoryBackendServiceFactory(this,this._InMemoryDbService_52,this._InMemoryBackendConfig_53)); }
    return this.__XHRBackend_54;
  }
  get _RequestOptions_55():import7.BaseRequestOptions {
    if ((this.__RequestOptions_55 == null)) { (this.__RequestOptions_55 = new import7.BaseRequestOptions()); }
    return this.__RequestOptions_55;
  }
  get _Http_56():any {
    if ((this.__Http_56 == null)) { (this.__Http_56 = import7.ɵc(this._XHRBackend_54,this._RequestOptions_55)); }
    return this.__Http_56;
  }
  get _BrowserXhr_57():import7.BrowserXhr {
    if ((this.__BrowserXhr_57 == null)) { (this.__BrowserXhr_57 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_57;
  }
  get _ResponseOptions_58():import7.BaseResponseOptions {
    if ((this.__ResponseOptions_58 == null)) { (this.__ResponseOptions_58 = new import7.BaseResponseOptions()); }
    return this.__ResponseOptions_58;
  }
  get _XSRFStrategy_59():any {
    if ((this.__XSRFStrategy_59 == null)) { (this.__XSRFStrategy_59 = import7.ɵb()); }
    return this.__XSRFStrategy_59;
  }
  get _HeroService_60():import10.HeroService {
    if ((this.__HeroService_60 == null)) { (this.__HeroService_60 = new import10.HeroService(this._Http_56)); }
    return this.__HeroService_60;
  }
  get _HeroSearchService_61():import11.HeroSearchService {
    if ((this.__HeroSearchService_61 == null)) { (this.__HeroSearchService_61 = new import11.HeroSearchService(this._Http_56)); }
    return this.__HeroSearchService_61;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import4.ɵa();
    this._NgProbeToken_2 = [import3.ɵb()];
    this._ɵg_3 = new import3.ɵg(this);
    this._APP_INITIALIZER_4 = [
      import0.ɵo,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_2),
      import3.ɵh(this._ɵg_3)
    ]
    ;
    this._ApplicationInitStatus_5 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_4);
    this._ɵf_6 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_5);
    this._ApplicationRef_7 = this._ɵf_6;
    this._ApplicationModule_8 = new import0.ApplicationModule(this._ApplicationRef_7);
    this._BrowserModule_9 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ɵba_10 = new import5.ɵba();
    this._FormsModule_11 = new import5.FormsModule();
    this._ɵa_12 = import3.ɵd(this.parent.get(import3.Router,(null as any)));
    this._UrlSerializer_13 = new import3.DefaultUrlSerializer();
    this._RouterOutletMap_14 = new import3.RouterOutletMap();
    this._ROUTER_CONFIGURATION_15 = {};
    this._LocationStrategy_16 = import3.ɵc(this.parent.get(import2.PlatformLocation),this.parent.get(import2.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_15);
    this._Location_17 = new import2.Location(this._LocationStrategy_16);
    this._Compiler_18 = new import0.Compiler();
    this._NgModuleFactoryLoader_19 = new import0.SystemJsNgModuleLoader(this._Compiler_18,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)));
      this._ROUTES_20 = [[
        {
          path: '',
          component: import16.DashboardComponent,
          pathMatch: 'full'
        }
        ,
        {
          path: 'heroes',
          component: import17.HeroesComponent
        }
        ,
        {
          path: 'dashboard',
          component: import16.DashboardComponent
        }
        ,
        {
          path: 'detail/:id',
          component: import18.HeroDetailComponent
        }

      ]
    ];
    this._Router_21 = import3.ɵe(this._ApplicationRef_7,this._UrlSerializer_13,this._RouterOutletMap_14,this._Location_17,this,this._NgModuleFactoryLoader_19,this._Compiler_18,this._ROUTES_20,this._ROUTER_CONFIGURATION_15,this.parent.get(import3.UrlHandlingStrategy,(null as any)),this.parent.get(import3.RouteReuseStrategy,(null as any)));
    this._RouterModule_22 = new import3.RouterModule(this._ɵa_12,this._Router_21);
    this._AppRoutingModule_23 = new import6.AppRoutingModule();
    this._HttpModule_24 = new import7.HttpModule();
    this._InMemoryWebApiModule_25 = new import8.InMemoryWebApiModule();
    this._AppModule_26 = new import1.AppModule();
    this._InMemoryBackendConfig_53 = (undefined as any);
    return this._AppModule_26;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_2; }
    if ((token === import3.ɵg)) { return this._ɵg_3; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_4; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_5; }
    if ((token === import0.ɵf)) { return this._ɵf_6; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_7; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_8; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_9; }
    if ((token === import5.ɵba)) { return this._ɵba_10; }
    if ((token === import5.FormsModule)) { return this._FormsModule_11; }
    if ((token === import3.ɵa)) { return this._ɵa_12; }
    if ((token === import3.UrlSerializer)) { return this._UrlSerializer_13; }
    if ((token === import3.RouterOutletMap)) { return this._RouterOutletMap_14; }
    if ((token === import3.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_15; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_16; }
    if ((token === import2.Location)) { return this._Location_17; }
    if ((token === import0.Compiler)) { return this._Compiler_18; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_19; }
    if ((token === import3.ROUTES)) { return this._ROUTES_20; }
    if ((token === import3.Router)) { return this._Router_21; }
    if ((token === import3.RouterModule)) { return this._RouterModule_22; }
    if ((token === import6.AppRoutingModule)) { return this._AppRoutingModule_23; }
    if ((token === import7.HttpModule)) { return this._HttpModule_24; }
    if ((token === import8.InMemoryWebApiModule)) { return this._InMemoryWebApiModule_25; }
    if ((token === import1.AppModule)) { return this._AppModule_26; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_27; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_28; }
    if ((token === import0.APP_ID)) { return this._APP_ID_29; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_32; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_33; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_34; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_35; }
    if ((token === import4.EventManager)) { return this._EventManager_36; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_37; }
    if ((token === import4.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_38; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_39; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_40; }
    if ((token === import0.Testability)) { return this._Testability_41; }
    if ((token === import4.Meta)) { return this._Meta_42; }
    if ((token === import4.Title)) { return this._Title_43; }
    if ((token === import5.ɵi)) { return this._ɵi_44; }
    if ((token === import3.ActivatedRoute)) { return this._ActivatedRoute_45; }
    if ((token === import3.NoPreloading)) { return this._NoPreloading_46; }
    if ((token === import3.PreloadingStrategy)) { return this._PreloadingStrategy_47; }
    if ((token === import3.RouterPreloader)) { return this._RouterPreloader_48; }
    if ((token === import3.PreloadAllModules)) { return this._PreloadAllModules_49; }
    if ((token === import3.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_50; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_51; }
    if ((token === import19.InMemoryDbService)) { return this._InMemoryDbService_52; }
    if ((token === import19.InMemoryBackendConfig)) { return this._InMemoryBackendConfig_53; }
    if ((token === import7.XHRBackend)) { return this._XHRBackend_54; }
    if ((token === import7.RequestOptions)) { return this._RequestOptions_55; }
    if ((token === import7.Http)) { return this._Http_56; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_57; }
    if ((token === import7.ResponseOptions)) { return this._ResponseOptions_58; }
    if ((token === import7.XSRFStrategy)) { return this._XSRFStrategy_59; }
    if ((token === import10.HeroService)) { return this._HeroService_60; }
    if ((token === import11.HeroSearchService)) { return this._HeroSearchService_61; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_6.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_37 && this._ɵDomSharedStylesHost_37.ngOnDestroy());
    (this.__RouterPreloader_48 && this._RouterPreloader_48.ngOnDestroy());
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory<any>(AppModuleInjector,import1.AppModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JoYXJhdGd1cHRhL0RvY3VtZW50cy9ndXB0YS9wcm9qZWN0cy9hbmd1bGFyMl9wcmFjdGljZS9xdWlja3N0YXJ0L3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9iaGFyYXRndXB0YS9Eb2N1bWVudHMvZ3VwdGEvcHJvamVjdHMvYW5ndWxhcjJfcHJhY3RpY2UvcXVpY2tzdGFydC9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
