/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.search-result[_ngcontent-%COMP%]{\n  border-bottom: 1px solid gray;\n  border-left: 1px solid gray;\n  border-right: 1px solid gray;\n  width:195px;\n  height: 16px;\n  padding: 5px;\n  background-color: white;\n  cursor: pointer;\n}\n.search-result[_ngcontent-%COMP%]:hover {\n  color: #eee;\n  background-color: #607D8B;\n}\n#search-box[_ngcontent-%COMP%]{\n  width: 200px;\n  height: 20px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2JoYXJhdGd1cHRhL0RvY3VtZW50cy9ndXB0YS9wcm9qZWN0cy9hbmd1bGFyMl9wcmFjdGljZS9xdWlja3N0YXJ0L3NyYy9hcHAvaGVyby1zZWFyY2guY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9iaGFyYXRndXB0YS9Eb2N1bWVudHMvZ3VwdGEvcHJvamVjdHMvYW5ndWxhcjJfcHJhY3RpY2UvcXVpY2tzdGFydC9zcmMvYXBwL2hlcm8tc2VhcmNoLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
